#!/bin/sh
BASE_DIR=~/Godot # Where this whole mess is sitting
BIN_DIR=$BASE_DIR/bin # Where godot executables are, in case path isn't setup
PROJECT=$BASE_DIR/Adamant # Which project are we working on again?
OUT_DIR=$BASE_DIR/build/linux # Where we send our built files to
PATH=$BIN_DIR:$PATH
ARCH="Linux/X11" # Prefix for export templates
ARGS="--path $PROJECT --quiet"
echo "Exporting Server"
godot-headless $ARGS --export-pack "$ARCH-Server" $OUT_DIR/Server.pck # Build the server pack
if [ ! -z "$1" ]
then
	clients=$1
	echo "Exporting Client"
	godot-headless $ARGS --export-debug "$ARCH-Client" $OUT_DIR/Client # Build the client executable
	while [ "$(($clients - 1))" -gt "-1" ]
	do
		clients="$(($clients - 1))"
		echo "Spawning Client #$((clients + 1))"
		$OUT_DIR/Client --resolution 1080x580--verbose & # Run the client in the background, we can close the window to kill it
	done
fi
echo "Spawning Server"
godot-server --main-pack $OUT_DIR/Server.pck # launch the server in foreground, we ^C to kill it
